services:
    feddit-db:
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

        image: postgis/postgis:14-3.2-alpine
    feddit-backend:
        depends_on:
            - feddit-db
        ports:
            - 8080:8080
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        build:
            context: ../feddit-backend

    feddit-frontend:
        depends_on:
            - feddit-backend
        ports:
            - ${NGINX_PORT}:${NGINX_PORT}
        build:
            context: ../feddit-frontend